### ISSUE TITLE
Why does 2023scripts get_ipids.py only parse NIMH?

### ISSUE THREAD

**Issue by joshlawrimore** [nimh-dsst/dsst-etl#1]
Test if the get_ipids.py in /scripts can parse the other ICs or not

**Comment by agt24** [comment]
This might have been a later modification. Pretty sure we parsed all ICs at some point

**Comment by joshlawrimore** [comment]
Confirmed that new git_ipids.py in [db9d842](https://github.com/nimh-dsst/sharestats-leo-notfork/commit/db9d842ff30d151a954c0b2a2374aa2567b07f56) is capable of parsing the ICs in the list
