### ISSUE TITLE
Rtransparent Publication Ingestion

### ISSUE THREAD

**Issue by joshlawrimore** [nimh-dsst/dsst-etl#10]
1. Create a schema for a table RTransparentPublication. This should match the columns in the data of the published csv file. This [schema class](https://github.com/nimh-dsst/osm/blob/main/osm/schemas/metrics_schemas.py#L11-L190) may be helpful in this task but make use of whatever types make most sense with Postgres/SQLAlchemy.
2. Write a script taking into account the following: 
  - It should take an input file (feather or parquet) that is a table containing published RTransparent metrics data
  - It should upload n rows (default 1000) rows of the data to the database
  - Each row of the data should create an entry in the RTransparentPublication table. 
  - Create and reference entries in the Work and  Provenance tables etc. as required.
  - The data should be written to the database as a bulk write operation for performance reasons.
  - Explicitly handle the fact that “Document” doesn’t exist here because we don’t have the source pdf. This may simply be a comment in the code with reasoning on the reference value/null value used. 
3. The work should be accompanied by an Alembic migration script
4. The work should include tests that write to a locally deployed postgres database (rollback each transaction)

**Comment by quang-ng** [comment]
Hi @joshlawrimore @leej3 if everything okay, could we merge PR #12 and close this issue?

**Comment by joshlawrimore** [comment]
> Hi [@joshlawrimore](https://github.com/joshlawrimore) [@leej3](https://github.com/leej3) if everything okay, could we merge PR [#12](https://github.com/nimh-dsst/dsst-etl/pull/12) and close this issue?

I was able to pull down your latest update and use the code to:

- Generate the postgres server using podman compose 
- Generate the `pdx` database manually using psql and pgadmin. Note, the name `pdx` I think is from a typo, but I like it as it implies "x number of pdfs." Please go ahead and keep it for now for dev.
- Use `alembic upgrade head` to generate the tables in the `pdx` database. I didn't verify the columns in the `rtransparent_publication` table were compatible with with what Rtransparent/Oddpub produce. I will leave that for the next issue.
- I was able to call `upload_directory` on a directory containing ~3500 pdfs. The S3 upload was successful and the tables appeared to populate correctly. I was able to run a few SQL queries on the resultant database. Note, I used a separate S3 bucket for testing.

From an end-user perspective, this looks good to me. 🎊 Great work 🎊  

There are some future enhancements that I would like to have, but I will open separate issues for those and address them myself in a separate PR. Thank you so much!

@leej3 could you please approve this once you are happy that your issues are fully addressed. Thanks!

**Comment by quang-ng** [comment]
thank you very much for you feedback. @joshlawrimore

**Comment by leej3** [comment]
Addressed by #12
